### ISSUE TITLE
Lot of errors on start. Images look corrupted

### ISSUE THREAD

**Issue by StoyanStAtanasov** [YaroslavHolovatyi/pokedex_angular_app#1]
When starting the project the app errors out with a lot of messages like
ERROR TypeError: Cannot read property 'sprites' of undefined

Can you please fix the issue?

**Comment by YaroslavHolovatyi** [comment]
The problem was with the usage of *ngFor and (click) for one division, but the error was resolved by adding *ngIf for the block with the pokemon information
